### ISSUE TITLE
BaseException.message has been deprecated as of Python 2.6

### ISSUE THREAD

**Issue by kyleabeauchamp** [counsyl/stor#15]
This warning is actually relevant for the py3k upgrade.  I'm making this a separate issue because it's something that we can address in a standalone PR without having to solve all the other py3k problems.

```
e = stor.exceptions.RemoteError('HEY')
DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
```

**Comment by jtratner** [comment]
I think you handled this
