### ISSUE TITLE
Tab completion installation instructions incompatible with pyenv

### ISSUE THREAD

**Issue by wesleykendall** [counsyl/stor#18]
When using the OSX installation instructions at https://counsyl.github.io/stor/installation.html#osx, running

```
`which stor-completion.bash`
```

will return the shim file from pyenv if one is using https://github.com/yyuu/pyenv. Copying this as a completion script results in failures since pyenv inserts header and footer code.

I'm not sure of a way to change the local installation instructions to handle this case just yet, but it might be better to simply have them instruct the user to download https://raw.githubusercontent.com/counsyl/stor/master/stor/stor-completion.bash directly and then copy it into the completion dir. Thoughts?

**Comment by jtratner** [comment]
Have you tried automating the installation with the `data_files` parameter?

http://stackoverflow.com/questions/3127388/including-bash-autocompletion-with-setuptools

**Comment by wesleykendall** [comment]
@jtratner that won't work out for installation on mac with homebrew and linux. I've tried a couple things to get this to work, like adding it to 'extra-files', but there is no easy way to find the path of an installed package without writing additional code (that I know of). Cool if I update the instructions to use a combination of curl and https://raw.githubusercontent.com/counsyl/stor/master/stor/stor-completion.bash? Open to other ideas

**Comment by jtratner** [comment]
whatever works - want to put up a PR?

**Comment by jtratner** [comment]
@wesleykendall ping here

**Comment by jtratner** [comment]
Fixed (implicitly) with #129 !

**Comment by jtratner** [comment]
Now you’d just do `stor completions > whatever.completions`
