### ISSUE TITLE
stor errors out when using pandas v0.23.1 

### ISSUE THREAD

**Issue by grepinsight** [counsyl/stor#77]
The following error occurs both in Python 3.6.4 and Python 2.7.15.

Running following code snippet gives an error when pandas version is `v0.23.1`:

```
import stor
import pandas as pd
pd.DataFrame({'a': [1,2,3,4,5,]})
tmp = pd.DataFrame({'a': [1,2,3,4,5,]})

with stor.open(<redacted>, "w") as fp:
    tmp.to_csv(fp, index=False)
```

It works fine when using `pandas==0.20.3`.

I made two virtual environments to isolate the problem, and the following is the `pip freeze` diffs between the two.
```
  ===>diff reqs.txt ../tmp/reqs.txt
44c44
< pandas==0.20.3
---
> pandas==0.23.1
```

**Comment by kdauria** [comment]
Also works fine for me when using `pandas==0.23.0`.

**Comment by jtratner** [comment]
This is fixed in newer versions of pandas (had to do with some incorrect inference about file objects). Tested your example in pandas==0.24.2 and it passed. Phew! :)
