### ISSUE TITLE
stor cp -r silently fails on individual files

### ISSUE THREAD

**Issue by kyleabeauchamp** [counsyl/stor#78]
Minor nit: if you do `stor cp -r` on an individual file (rather than a dir), it silently fails.  The usual POSIX behavior (IMHO) is to just copy the file.

**Comment by jtratner** [comment]
Yes, this goes back to “we can’t tell if things are actually objects or
directories on OBS”. So -r is equivalent to saying “everything with this
prefix”. It is, however, a bummer :(

**Comment by jtratner** [comment]
closing cuz this is actually... basically limitation of how OBS paths work generally...
