### ISSUE TITLE
Travis python 3.5 tests run python 2.7 tests

### ISSUE THREAD

**Issue by jtratner** [counsyl/stor#8]
I had random late-night inspiration to try to write type annotations for stor so we could play around with mypy.  That led to me trying to run mypy's annotation checker (that defaults to python3 ) and realizing that we were using libraries like cStringIO.

We should probably remove `3.5` tests from Travis until we actually make it compatible with 3.5 (or run 2to3 on it and then test).

**Comment by lucaswiman** [comment]
Isn't `cStringIO` deprecated in favor of `io.BytesIO` in Python 2? BytesIO is also implemented in C and is Python 3 compatible: see https://github.com/python/cpython/blob/2.7/Modules/_io/bytesio.c and https://github.com/python/cpython/blob/2.7/Lib/io.py

**Comment by jtratner** [comment]
Exactly the point ;) cStringIO isn't in Python 3 at all, supporting my
assertion that we've never made this library python 3 compatible.

**Comment by kyleabeauchamp** [comment]
There's also `io.stringio`.  I ran `futurize` on `stor` and it tries to make that substitution throughout:

```
@@ -276,9 +280,9 @@ class OBSFile(object):
     def _buffer(self):
         "Cached buffer of data read from or to be written to Object Storage"
         if self.mode in ('r', 'rb'):
-            return cStringIO.StringIO(self._path.read_object())
+            return io.StringIO(self._path.read_object())
         elif self.mode in ('w', 'wb'):
-            return cStringIO.StringIO()
+            return io.StringIO()
         else:
             raise ValueError('cannot obtain buffer in mode: %r' % self.mode)

```

**Comment by kyleabeauchamp** [comment]
My untested, futurized branch is here:

https://github.com/counsyl/stor/compare/master...kyleabeauchamp:py3k?expand=1

**Comment by kyleabeauchamp** [comment]
This can be closed AFAIK
